apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azzu-clusterrole
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "create", "update", "delete"]

