apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azzu-read-only-role-binding
  namespace: med-dev
subjects:
- kind: User
  name: azzu
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-only-pod-role
  apiGroup: rbac.authorization.k8s.io

