apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: med-dev
  name: registration-form
  labels:
    app: registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      name: registration
      labels:
        app: registration
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  # Fixed the typo
            nodeSelectorTerms:
              - matchExpressions:  # Fixed the typo
                - key: "env"
                  operator: In
                  values:
                    - "dev"
                    - "uat"
      containers:
        - name: registration-form
          image: mohammadaszadali/registrationform:12
          imagePullPolicy: IfNotPresent  # Fixed the typo
          ports:
            - containerPort: 80

