apiVersion: v1
kind: Service
metadata:
  namespace: med-dev
  name: loginform-svc
  labels:
    app: login-form
spec:
  selector:
    app: login-form
  type: NodePort
  ports:
    - port: 80
      nodePort: 32766
      targetPort: 80

