apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: med-dev
  name: registrationform
  labels:
    app: registrationform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registrationform
  template:
    metadata: 
      labels:
        app: registrationform
    spec:
      nodeName: ip-172-31-44-53
      containers:
      - name: registrationform
        image: mohammadaszadali/registrationform:12
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /reg.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /reg.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10 
          failureThreshold: 3

