apiVersion: v1
kind: Service
metadata:
  namespace: med-dev
  name: registration-svc
  labels:
    app: registrationform
spec:
  selector:
    app: registrationform
  type: NodePort
  ports:
    - port: 80
      nodePort: 32767
      targetPort: 80

